export const mockData = {
  userInfo: {
    userId: "user_001",
    nickName: "TennisFan",
    avatarUrl: "/images/default-avatar.png",
    gender: 1,
    age: 25,
    level: "3.5",
    bio: "Love tennis!",
    creditScore: 100,
    createdAt: "2023-01-01"
  },
  courts: [
    {
      courtId: "court_001",
      name: "City Tennis Center",
      address: "123 Main St",
      latitude: 30.0,
      longitude: 120.0,
      phone: "123-456-7890",
      businessHours: "08:00-22:00",
      rating: 4.5,
      reviewCount: 100,
      pricePerHour: 50,
      surfaceType: "Hard",
      indoor: false,
      hasLights: true,
      amenities: ["Parking", "Shower"],
      available: true
    },
    {
      courtId: "court_002",
      name: "Green Park Tennis",
      address: "456 Park Ave",
      latitude: 30.1,
      longitude: 120.1,
      phone: "987-654-3210",
      businessHours: "09:00-21:00",
      rating: 4.8,
      reviewCount: 50,
      pricePerHour: 80,
      surfaceType: "Clay",
      indoor: true,
      hasLights: true,
      amenities: ["Parking", "Lounge"],
      available: true
    },
    {
      courtId: "court_003",
      name: "Riverside Tennis Club",
      address: "789 River Rd",
      latitude: 30.2,
      longitude: 120.2,
      phone: "555-123-4567",
      businessHours: "07:00-23:00",
      rating: 4.9,
      reviewCount: 210,
      pricePerHour: 120,
      surfaceType: "Grass",
      indoor: false,
      hasLights: true,
      amenities: ["Parking", "Shower", "Cafe", "Pro Shop"],
      available: true
    },
    {
      courtId: "court_004",
      name: "Community Sports Park",
      address: "321 Community Ln",
      latitude: 29.9,
      longitude: 119.9,
      phone: "555-987-6543",
      businessHours: "06:00-22:00",
      rating: 4.2,
      reviewCount: 85,
      pricePerHour: 30,
      surfaceType: "Hard",
      indoor: false,
      hasLights: true,
      amenities: ["Parking", "Vending Machine"],
      available: true
    },
    {
      courtId: "court_005",
      name: "Elite Indoor Tennis",
      address: "888 Elite Way",
      latitude: 30.3,
      longitude: 120.3,
      phone: "555-888-8888",
      businessHours: "24 Hours",
      rating: 5.0,
      reviewCount: 150,
      pricePerHour: 150,
      surfaceType: "Carpet",
      indoor: true,
      hasLights: true,
      amenities: ["Parking", "Shower", "Sauna", "Gym", "Lounge"],
      available: false
    }
  ],
  matches: [
    {
      matchId: "match_001",
      publisherId: "user_002",
      courtId: "court_001",
      courtName: "City Tennis Center",
      date: "2025-12-31",
      startTime: "18:00",
      endTime: "20:00",
      matchType: "Singles",
      levelMin: 3.0,
      levelMax: 4.0,
      currentPlayers: 1,
      maxPlayers: 2,
      costType: "AA",
      costPerPerson: 50,
      description: "Looking for a hitting partner.",
      status: "Open",
      createdAt: "2025-12-30",
      distance: 1.5
    },
    {
      matchId: "match_002",
      publisherId: "user_003",
      courtId: "court_002",
      courtName: "Green Park Tennis",
      date: "2026-01-01",
      startTime: "14:00",
      endTime: "16:00",
      matchType: "Doubles",
      levelMin: 3.5,
      levelMax: 4.5,
      currentPlayers: 3,
      maxPlayers: 4,
      costType: "AA",
      costPerPerson: 40,
      description: "Need one more for doubles! Fun game.",
      status: "Open",
      createdAt: "2025-12-30",
      distance: 3.2
    },
    {
      matchId: "match_003",
      publisherId: "user_004",
      courtId: "court_004",
      courtName: "Community Sports Park",
      date: "2026-01-02",
      startTime: "09:00",
      endTime: "11:00",
      matchType: "Singles",
      levelMin: 2.0,
      levelMax: 3.0,
      currentPlayers: 1,
      maxPlayers: 2,
      costType: "Free",
      costPerPerson: 0,
      description: "Beginner practice. Just rallying.",
      status: "Open",
      createdAt: "2025-12-29",
      distance: 5.0
    },
    {
      matchId: "match_004",
      publisherId: "user_005",
      courtId: "court_005",
      courtName: "Elite Indoor Tennis",
      date: "2026-01-03",
      startTime: "19:00",
      endTime: "21:00",
      matchType: "Doubles",
      levelMin: 4.5,
      levelMax: 5.5,
      currentPlayers: 4,
      maxPlayers: 4,
      costType: "Fixed",
      costPerPerson: 100,
      description: "High level doubles match.",
      status: "Full",
      createdAt: "2025-12-28",
      distance: 8.5
    },
    {
      matchId: "match_005",
      publisherId: "user_006",
      courtId: "court_003",
      courtName: "Riverside Tennis Club",
      date: "2026-01-04",
      startTime: "10:00",
      endTime: "12:00",
      matchType: "Singles",
      levelMin: 3.0,
      levelMax: 3.5,
      currentPlayers: 1,
      maxPlayers: 2,
      costType: "AA",
      costPerPerson: 60,
      description: "Morning hit on grass.",
      status: "Open",
      createdAt: "2025-12-30",
      distance: 12.0
    }
  ]
};
